### ISSUE TITLE
Server issue after upgrading to [10.7.0] - 2022-10-29 

### ISSUE THREAD

**Issue by houser42** [windkh/node-red-contrib-shelly#101]
Hello,
It could be something else of course, but I can not start my node red server after upgrading to 
[10.7.0] - 2022-10-29. Is there a possibility that there is something wrong in that package?
[10.6.0] - 2022-10-28 was working fine. Grateful for a comment.

**Comment by windkh** [comment]
What node version do you have?

**Comment by windkh** [comment]
I just removed dependency to crypto and fs as they are integrated into node... but it could be that this is only available in a later node version

**Comment by houser42** [comment]
> I just removed dependency to crypto and fs as they are integrated into node... but it could be that this is only available in a later node version

I see. I am not by the server, but I can say that it is less than v14.17.6 as there is an update available to that version; nodejs to v14.17.6 in the link branch I am using.

**Comment by houser42** [comment]
Can you comment on which versions I need for your 10.7 version to be supported please?

**Comment by windkh** [comment]
Is somethi g printed in the nodered console? So that I know what package caused the problems?

**Comment by houser42** [comment]
> Is somethi g printed in the nodered console? So that I know what package caused the problems?

As it stands I can not start the node red server after the upgrade de [node-red-contrib-shelly](https://github.com/windkh/node-red-contrib-shelly) 10.7 s

**Comment by windkh** [comment]
Why did you close it?

**Comment by windkh** [comment]
I can revert the changes if required... don't know by heart what node version supports crypto

**Comment by houser42** [comment]
That is your expertise and I am afraid I can not say anything about that. 
I can just say that on this particular branch this change disrupts the node red flows and makes the server unresponsive.

**Comment by houser42** [comment]
So I got the server up again by safe booting it.. My problem is that I only have access to this particular site install via the Node Red webgui, so I can’t downgrade AFAIK.
 Grateful for an helpful hints if you have any.

**Comment by windkh** [comment]
I will revert the changes and create a new version

**Comment by windkh** [comment]
V10.8.0 should fix it

**Comment by houser42** [comment]
I am sorry to report that I am still having issues after this upgrade.
I am unable to get this install working again, even after a complete whip and reinstall.
I keep seeing this, even after a vanilla reinstall. Is it possible that something has gone wrong in the code?
Can I go back to 10.5 that worked perfectly from a terminal reinstall? Sorry about this and thanks for your patience.

<img width="444" alt="Screenshot 2022-11-01 at 20 18 44" src="https://user-images.githubusercontent.com/15192440/199322289-2521bc51-8f62-4f0f-a8ca-98aa7ddd1f0f.png">

**Comment by windkh** [comment]
I will install it on my own right now... gimme a few minutes

**Comment by windkh** [comment]
installed correctly on node-red 3.0.2, nodejs 16.6.0

**Comment by windkh** [comment]
what does the node-red console output say?

**Comment by houser42** [comment]
I can install it too but have you tried deploying a node or two? This error comes after a deploy,

**Comment by windkh** [comment]
yes, everything works as expected.

**Comment by windkh** [comment]
We need to find out what module was not found: for  that reason the console output is needed

**Comment by windkh** [comment]
maybe it is the path dependency
const path = require('node:path');

**Comment by windkh** [comment]
just pushed 10.9.0 with a changed path require. Please try it.

**Comment by windkh** [comment]
I mean 10.9.1

**Comment by houser42** [comment]
Ok. Will try its as soon as I see it. NR server is 3.02 and nodejs is  v14.17.6 FYI.

**Comment by houser42** [comment]
Yes! That appears to have fixed it. Working on getting the site up again, but pretty sure that was the  issue.
Appreciate your prompt help enormously!
