### ISSUE TITLE
Error: getaddrinfo ENOTFOUND undefined 

### ISSUE THREAD

**Issue by Lineflyer** [windkh/node-red-contrib-shelly#163]
Today I upgraded `node-red-contrib-shelly` coming from V10.13.7 to current V10.27.0

After rebooting Node Red to activate the update all shelly functions act normal besides the connection to the single Shelly Plug S (Gen1) I have in my network.

Flows were working smooth before, but now the `shelly gen 1` node cycles between connected and the error state `Error: getaddrinfo ENOTFOUND undefined` in intervals of 1-2 seconds.

This is the simple configuration I use:
![image](https://github.com/windkh/node-red-contrib-shelly/assets/949669/5d98ecc1-f2c6-4af6-ba7c-afcbedb0d60b)
![image](https://github.com/windkh/node-red-contrib-shelly/assets/949669/a752a82a-9392-4cef-8ba4-6734731623a5)

One strange thing I noticed while trying to debug:
If I try to autodetect the device type it returns an incorrect type `Relay SHPLG-S`. Once I try to use it the node reports a type mismatch.
When I change it back to `Plug(S/E/US)` the problem described above rises again.

Plug S is using newest available firmware.
Any advice?

**Comment by windkh** [comment]
@Lineflyer 
ah that is interesting.
I have a shelly plug s here and I will try to reproduce it. Thanks for reporting.

I refactored a lot of stuff yesterday in order to get rid of strange exceptions. Maybe I am causing additional state changes... will try to fix it asap.

**Comment by windkh** [comment]
fixed in 10.27.1 
thanks alot, did not see that

**Comment by Splinti** [comment]
Hi @windkh 
The problem seems to persist when i'm using 10.27.1 and my Shelly Gen1 2.5 Relay.
Downgrading the package to a lower version fixes the issue.

**Comment by Lineflyer** [comment]
@windkh 

I also just upgraded to v10.27.1 + restart to try it out and I also have to confirm:
Error is still there as described initially. Let me know, if you need more info/logs or anything.

**Comment by windkh** [comment]
Hm ...? 
If you have a log then paste it here

**Comment by Lineflyer** [comment]
Well, the normal node-red log only shows the following from both nodes where I use this shelly:
```
8 Jul 19:49:11 - [warn] [shelly-gen1:f929ead30743b4b2] Error: Error: getaddrinfo ENOTFOUND undefined
8 Jul 19:49:16 - [warn] [shelly-gen1:8ba7704f650825c6] Error: Error: getaddrinfo ENOTFOUND undefined
8 Jul 19:49:16 - [warn] [shelly-gen1:f929ead30743b4b2] Error: Error: getaddrinfo ENOTFOUND undefined
8 Jul 19:49:21 - [warn] [shelly-gen1:8ba7704f650825c6] Error: Error: getaddrinfo ENOTFOUND undefined
8 Jul 19:49:21 - [warn] [shelly-gen1:f929ead30743b4b2] Error: Error: getaddrinfo ENOTFOUND undefined
8 Jul 19:49:26 - [warn] [shelly-gen1:8ba7704f650825c6] Error: Error: getaddrinfo ENOTFOUND undefined
8 Jul 19:49:26 - [warn] [shelly-gen1:f929ead30743b4b2] Error: Error: getaddrinfo ENOTFOUND undefined
8 Jul 19:49:31 - [warn] [shelly-gen1:8ba7704f650825c6] Error: Error: getaddrinfo ENOTFOUND undefined
8 Jul 19:49:31 - [warn] [shelly-gen1:f929ead30743b4b2] Error: Error: getaddrinfo ENOTFOUND undefined
8 Jul 19:49:36 - [warn] [shelly-gen1:8ba7704f650825c6] Error: Error: getaddrinfo ENOTFOUND undefined
8 Jul 19:49:36 - [warn] [shelly-gen1:f929ead30743b4b2] Error: Error: getaddrinfo ENOTFOUND undefined
8 Jul 19:49:41 - [warn] [shelly-gen1:8ba7704f650825c6] Error: Error: getaddrinfo ENOTFOUND undefined
8 Jul 19:49:41 - [warn] [shelly-gen1:f929ead30743b4b2] Error: Error: getaddrinfo ENOTFOUND undefined
8 Jul 19:49:46 - [warn] [shelly-gen1:8ba7704f650825c6] Error: Error: getaddrinfo ENOTFOUND undefined
8 Jul 19:49:46 - [warn] [shelly-gen1:f929ead30743b4b2] Error: Error: getaddrinfo ENOTFOUND undefined
8 Jul 19:49:51 - [warn] [shelly-gen1:8ba7704f650825c6] Error: Error: getaddrinfo ENOTFOUND undefined
8 Jul 19:49:51 - [warn] [shelly-gen1:f929ead30743b4b2] Error: Error: getaddrinfo ENOTFOUND undefined
8 Jul 19:49:56 - [warn] [shelly-gen1:8ba7704f650825c6] Error: Error: getaddrinfo ENOTFOUND undefined
8 Jul 19:49:56 - [warn] [shelly-gen1:f929ead30743b4b2] Error: Error: getaddrinfo ENOTFOUND undefined
8 Jul 19:50:01 - [warn] [shelly-gen1:8ba7704f650825c6] Error: Error: getaddrinfo ENOTFOUND undefined
8 Jul 19:50:01 - [warn] [shelly-gen1:f929ead30743b4b2] Error: Error: getaddrinfo ENOTFOUND undefined
8 Jul 19:50:06 - [warn] [shelly-gen1:8ba7704f650825c6] Error: Error: getaddrinfo ENOTFOUND undefined
8 Jul 19:50:06 - [warn] [shelly-gen1:f929ead30743b4b2] Error: Error: getaddrinfo ENOTFOUND undefined
8 Jul 19:50:11 - [warn] [shelly-gen1:8ba7704f650825c6] Error: Error: getaddrinfo ENOTFOUND undefined
8 Jul 19:50:11 - [warn] [shelly-gen1:f929ead30743b4b2] Error: Error: getaddrinfo ENOTFOUND undefined
8 Jul 19:50:16 - [warn] [shelly-gen1:8ba7704f650825c6] Error: Error: getaddrinfo ENOTFOUND undefined
8 Jul 19:50:16 - [warn] [shelly-gen1:f929ead30743b4b2] Error: Error: getaddrinfo ENOTFOUND undefined
```

**Comment by windkh** [comment]
please install V10.27.3 and let me know if it helps

**Comment by Splinti** [comment]
This fixed it for me, thank you! :)

**Comment by Lineflyer** [comment]
Confirmed fixed with v10.27.3 
Thanks @windkh for this swift reaction. Appreciated!

**Comment by windkh** [comment]
Thank you all for your help!
