### ISSUE TITLE
Error in executeCommand1

### ISSUE THREAD

**Issue by I-am-a-node** [windkh/node-red-contrib-shelly#168]
Hi, I don't know if this error message has a connection to any of the latest versions released. I have never seen this before and suddenly it pops up after the upgrading to v 10.28.1. 

_Versions: I've seen there has been a few updates lately so might have missed one and cant say exactly the exact version that might have brought this. At the same time I am looking at others reasons what that might be._

The error message is random in blocks, meaning I have 6 nodes in a flow on one computer. All 6 produces the error message at the same time. Also  have 1 test flow with 2 nodes installed in a testing environment on another linux computer, same thing there. Could be random or when deploying after another change. However have been using "Modified Nodes" .

**Question.** Do I have to open all previously added nodes and close with DONE and DEPLOY to catch a _new_ setting? As if I made a new change to a setting? Meaning the settings has to be kind of updated with something new that you've added to the node?

I'll keep an eye on this and see if I can see a pattern.

**Edit/update 23rd July 2024.**
There seem to be plenty more of those error messages. Listing them below. 
Never seen these before.
All from the different kinds of units. EM, Plug, Plus 1 PM, 1PM Mini, Dimmer 2. 

**Edit/update 24th July 2024.**
Did a check on my network thinking there was a connectivity issue. However, nothing has changed with the network lately. Did a restart to see if there as a change in behaviour and how they stay connected. Created a setup up with testing during the night but could not find any fault. Also no firmware has been changed on any of they Shellys. The only thing that has changed is the update of the Shelly nodes in Node-Red. 

I'll have to create my own setup with config using the a flow with api to avoid using the Shelly node so and hope I wont get these errors as they are causing issues to my system.

Error message:

> "Error in executeCommand1: /status  --> AxiosError: timeout of 5012ms exceeded"

> "Error in executeCommand2: /rpc/Shelly.GetStatus  --> AxiosError: timeout of 5022ms exceeded"

**Comment by reini12345** [comment]
same for me. Additionally i get "Error: read ECONNRESET" for some nodes after e.g. after sending an on or off command to a shelly node

**Comment by windkh** [comment]
@reini12345 can you test one of the examples if it works then?

**Comment by reini12345** [comment]
i use this code to switch a shelly1plus off:

```
msg.payload = {
    method: "Switch.Set",
    parameters: {
        id: 0,
        on: false,
    }
};
return msg;
```

**Comment by windkh** [comment]
I am currently not at home. Will check it out when I am back.

**Comment by I-am-a-node** [comment]
@reini12345  I will untick both "status output" options to get rid of all the error messages (hoping this works). Not ideal but don't think I have a choice if I don't want to get flooded with errors. 
I'm pretty sure I've unticked them before and when updated the pervious setting has gone back to default.

If you have the time. Please let me know if it works when sending your commands? I will run with this for about 24 hours to see if it helps.

![Untick](https://github.com/user-attachments/assets/cca2521f-bcec-4412-8157-4825a6bfc178)

**Comment by reini12345** [comment]
@I-am-a-node deactivate these options is not a valid option for me, because i need it to save the status in an influxdb and sending the status with pushover

![image](https://github.com/user-attachments/assets/b32c72dc-3e62-4de4-8a6f-7c954ba676ed)

**Comment by I-am-a-node** [comment]
@reini12345 Thanks for your reply. Yea, kind if figured that you're using the status in your function. Think it might be the users who does need it for propose that get annoyed by these errors. 

Curious if this is down to a programming structure, a change in the Axios libraries, or if it's only down to poor connection within the home network. If that is the case it would be good to have the option to set/change the timeout. Now I am trying to figure out if this issue has any other implication on my functions. To see how I can capture an error and implement this into the function to re-do a manual action to repair, ensure the event/action gets the data/push the action when an error occurs.

**Comment by I-am-a-node** [comment]
@windkh let me know if you need any additional information from us regarding experiences from using the node. Or if you want help with testing. My programming skills are limited so... hope I can help with providing info and/or testing.

**Comment by windkh** [comment]
A sample flow would be useful so that I can reproduce it. 
Will fix it after my vacation

**Comment by reini12345** [comment]
@windkh no problem: 

`[{"id":"d7b3ff9c5ae8cffd","type":"function","z":"7947c8eb71b89e19","g":"de33c669c2e86fc3","name":"","func":"msg.payload = msg.payload.switch0.output;\nreturn msg;","outputs":1,"timeout":"","noerr":0,"initialize":"","finalize":"","libs":[],"x":420,"y":4600,"wires":[["1718314b51346f2d","87695cbacdf4750e"]]},{"id":"0a4878cb293c140b","type":"debug","z":"7947c8eb71b89e19","g":"de33c669c2e86fc3","name":"debug 150","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":430,"y":4640,"wires":[]},{"id":"2fb57078ce6ffbfe","type":"function","z":"7947c8eb71b89e19","g":"de33c669c2e86fc3","name":"UG.Keller.Aussen.Lampe off","func":"msg.payload = {\n    method: \"Switch.Set\",\n    parameters: {\n        id: 0,\n        on: false,\n    }\n};\nreturn msg;","outputs":1,"timeout":"","noerr":0,"initialize":"","finalize":"","libs":[],"x":560,"y":4540,"wires":[["a76ba26b08a34d69"]]},{"id":"0d502437e6d4a08e","type":"inject","z":"7947c8eb71b89e19","g":"de33c669c2e86fc3","name":"UG.Keller.Aussen.Lampe.AutoAus.Uhrzeit","props":[{"p":"payload"}],"repeat":"","crontab":"00 02 * * *","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":230,"y":4540,"wires":[["2fb57078ce6ffbfe"]]},{"id":"a76ba26b08a34d69","type":"shelly-gen2","z":"7947c8eb71b89e19","g":"de33c669c2e86fc3","hostname":"192.168.178.128","description":"UG.Keller.Aussen.Lampe ","mode":"polling","verbose":false,"server":"","outputmode":"event","uploadretryinterval":5000,"pollinginterval":"3600000","pollstatus":true,"getstatusoncommand":true,"devicetype":"Relay","devicetypemustmatchexactly":false,"outputs":1,"x":190,"y":4600,"wires":[["d7b3ff9c5ae8cffd","0a4878cb293c140b"]]}]`

**Comment by windkh** [comment]
> same for me. Additionally i get "Error: read ECONNRESET" for some gen2 device nodes e.g. after sending an on or off command to the node

this is  fixed in 10.28.2 (see #172)

**Comment by I-am-a-node** [comment]
@reini12345 Did this get solved for you? I still get get flooded with the error messages.

**Comment by I-am-a-node** [comment]
@windkh Hi, I wonder if mange to find anything on the matter of the "AxiosError: timeout" error messages? 

Would like to continue using your node. However I still get flooded and am drowning in these error messages. Have tried different ways of not getting them. Stopped using the "pull" function + unticked the status messages and tried to request data by an inject node. However that doesn't help.

**Comment by windkh** [comment]
I did some changes, but I still need some testing... 
did nothing change with the last release?

**Comment by I-am-a-node** [comment]
@windkh Oki. Thank you for getting back on this. Appreciate that you're taking your time. 
Let me know if you need any help.

**Comment by reini12345** [comment]
> @reini12345 Did this get solved for you? I still get get flooded with the error messages.

Yes, this error has been fixed. But I still have Axios Error restarting the NodeRed and EHOSTUNREACH Error, although the devices can be reached normally. 
![image](https://github.com/user-attachments/assets/334b9377-0a33-45c1-811d-ed0736860a29)

**Comment by reini12345** [comment]
I haven't seen the error recently. If I see it again then I'll try to log it

**Comment by windkh** [comment]
@I-am-a-node 
as the errors disappeared we should focus on your specific problems: can you send me your flow so that I can reproduce it?

**Comment by reini12345** [comment]
@windkh got this error some minutes ago which lead to a restart of Node-RED:

16 Sep 09:21:43 - [red] Uncaught Exception:
16 Sep 09:21:43 - [error] AxiosError: timeout of 5022ms exceeded
    at RedirectableRequest.handleRequestTimeout (/data/node_modules/node-red-contrib-shelly/node_modules/axios/lib/adapters/http.js:647:16)
    at RedirectableRequest.emit (node:events:519:28)
    at Timeout.<anonymous> (/data/node_modules/follow-redirects/index.js:210:12)
    at listOnTimeout (node:internal/timers:581:17)
    at processTimers (node:internal/timers:519:7)
    at Axios.request (/data/node_modules/node-red-contrib-shelly/node_modules/axios/lib/core/Axios.js:45:41)
16 Sep 09:21:44 - [info] 
Welcome to Node-RED
===================
16 Sep 09:21:44 - [info] Node-RED version: v4.0.2
16 Sep 09:21:44 - [info] Node.js  version: v20.17.0
16 Sep 09:21:44 - [info] Linux 6.2.16-4-pve x64 LE
16 Sep 09:21:44 - [info] Loading palette nodes
16 Sep 09:21:46 - [info] node-red-contrib-ccu version: 3.4.2
16 Sep 09:21:46 - [info] Dashboard version 3.4.0 started at /ui
16 Sep 09:21:47 - [warn] ---------------------------------------------

**Comment by windkh** [comment]
@reini12345 please upgrade to 11.0.1 and let me know if something changed.

**Comment by windkh** [comment]
Please update to 11.3 and let me know if something improved

**Comment by reini12345** [comment]
![5gDHCYfe1h](https://github.com/user-attachments/assets/bcfe490c-0e3b-425b-b41b-cf8dea55835f)

no change here. Gen1 and Gen2 devices are affected.

**Comment by Subnum12** [comment]
...same with 11.5.3

**Comment by tossa-fan** [comment]
...same here with 11.5.7

**Comment by windkh** [comment]
Is this still a problem?

**Comment by windkh** [comment]
closed to no activity

**Comment by mzolling** [comment]
Hello,
I am using shelly gen 2+ nodes to manage 12 Shelly Pro 1 v.1 switches; purpose is to monitor their status, particularly focusing on online / offline status.
- If a node is up it's shown as connected and I get full status payloads from the shelly node
- if a node wasn't up yet, the shelly node shows "waiting for device..."
- if a node was previously online then was turned off, the node shows: "Error: Error: connect EHOSTUNREACH 192.168.185.104:80" and does NOT output any payload, not even msg.error
- in that case the Node-red debug screen shows: msg : string [99] - "Error in executeCommand2: /rpc/Shelly.GetStatus  --> Error: connect EHOSTUNREACH 192.168.185.104:80"; this status does not change until the switch gets back online or I redeploy the flow

This obviously does not serve my purpose, I'll probably go back to simple http polling

Marco
